openapi: 3.1.0
components:
  schemas:
    BusinessHoursResponse:
      type: object
      properties:
        result:
          type: string
          description: Resultado del cálculo
        startDate:
          type: string
          format: date-time
          description: Fecha de inicio del período calculado
        endDate:
          type: string
          format: date-time
          description: Fecha final del período calculado
        totalBusinessHours:
          type: number
          description: Total de horas hábiles calculadas
        totalBusinessDays:
          type: number
          description: Total de días hábiles calculados
        businessHours:
          type: number
          description: Horas hábiles
        days:
          type: number
          description: Días
        hours:
          type: number
          description: Horas
        minutes:
          type: number
          description: Minutos
      required:
        - startDate
        - endDate
        - totalBusinessHours
        - totalBusinessDays
        - businessHours
        - days
        - hours
        - minutes
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: number
        error:
          type: string
        message:
          type: string
        code:
          type: string
      required:
        - statusCode
        - error
        - message
  securitySchemes: {}
info:
  title: Working Days API
  description: API para el cálculo de días y horas hábiles
  version: 1.0.0
paths:
  //business-hours:
    get:
      operationId: businessHours
      summary: Obtiene horarios comerciales
      description: Retorna los horarios comerciales basados en parámetros de consulta
      tags:
        - Business Hours
      responses:
        '200':
          description: Horarios comerciales obtenidos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessHoursResponse'
        '400':
          description: Parámetros de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
